# 

# It all starts with imports, as usual !

In [12]:
'''Import Pytorch and if you have CUDA, take advantage of it.pssst: I dont!'''
import torch
import torch.optim as optim
import torch.nn as nn
import numpy as np

'''Do you have CUDA, Hmm what even is CUDA?'''
device = 'cuda' if torch.cuda.is_available() else 'cpu'

C:\Users\Jordan Lian\anaconda3\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


# One Tensor (array) to numpy them with

In [14]:
'''Have you heard data is king?'''
np.random.seed(42)
x = np.random.rand(1000, 1)
y = 1 + 2 * x + .1 * np.random.randn(1000, 1)

'''No index will be left unrandomized oln my watch'''

idx = np.arange(1000)
np.random.shuffle(idx)

'''First 700 random indices for train'''

train_idx = idx[:700]

'''And the remaining indices for validation'''
val_idx = idx[700:]

'''Generates train and validation sets'''

x_train, y_train = x[train_idx], y[train_idx]
x_val, y_val = x[val_idx], y[val_idx]

# One tensor to pyTorch them with

In [15]:

'''Our data was in Numpy arrays,  transform them into PyTorch's Tensors
and then we send them to the chosen device (As if I had a choice)'''

x_train_tensor = torch.from_numpy(x_train).float().to(device)
y_train_tensor = torch.from_numpy(y_train).float().to(device)

''' .type() tells us WHERE the tensor lives'''

print(type(x_train), type(x_train_tensor), x_train_tensor.type())

<class 'numpy.ndarray'> <class 'torch.Tensor'> torch.FloatTensor


# And with one tensor train them !

In [16]:
a = torch.randn(1, dtype=torch.float).to(device)
b = torch.randn(1, dtype=torch.float).to(device)

'''Require gradients, else you might as well use numpy'''

a.requires_grad_()
b.requires_grad_()
print(a, b)

'''When you add _, you will lose change them in place...'''

tensor([0.2264], requires_grad=True) tensor([2.0406], requires_grad=True)


'When you add _, you will lose change them in place...'

In [17]:
'''Old friend learning rate is back !Epochs too...'''
lr = 1e-1
n_epochs = 1000

torch.manual_seed(42)
a = torch.randn(1, requires_grad=True, dtype=torch.float, device=device)
b = torch.randn(1, requires_grad=True, dtype=torch.float, device=device)


In [18]:
'''And the loopy loop for updating the parameters...'''

for epoch in range(n_epochs):
    yhat = a + b * x_train_tensor
    error = y_train_tensor - yhat
    loss = (error ** 2).mean()
    
    '''Backwards from the loss'''
    loss.backward()
    
    '''Don't trust me, print the computed gradients...'''
    print(a.grad)
    print(b.grad)
    
    '''Parameters...update them...see below'''
        
    
    '''NO_GRAD keeps the update out of the gradient computation
    Why? Well, it's because of the dynamic graph from PyTorch'''
    
    with torch.no_grad():
        a -= lr * a.grad
        b -= lr * b.grad
    
    '''Let it go, let it gooo PyTorch, dont catch the computed gradients'''
    a.grad.zero_()
    b.grad.zero_()
    
print(a, b)

tensor([-3.2047])
tensor([-1.9083])
tensor([-2.3739])
tensor([-1.4628])
tensor([-1.7536])
tensor([-1.1295])
tensor([-1.2905])
tensor([-0.8800])
tensor([-0.9448])
tensor([-0.6932])
tensor([-0.6869])
tensor([-0.5532])
tensor([-0.4944])
tensor([-0.4482])
tensor([-0.3510])
tensor([-0.3692])
tensor([-0.2440])
tensor([-0.3098])
tensor([-0.1644])
tensor([-0.2649])
tensor([-0.1052])
tensor([-0.2310])
tensor([-0.0611])
tensor([-0.2052])
tensor([-0.0285])
tensor([-0.1855])
tensor([-0.0043])
tensor([-0.1704])
tensor([0.0135])
tensor([-0.1586])
tensor([0.0266])
tensor([-0.1494])
tensor([0.0361])
tensor([-0.1422])
tensor([0.0430])
tensor([-0.1363])
tensor([0.0480])
tensor([-0.1315])
tensor([0.0515])
tensor([-0.1276])
tensor([0.0539])
tensor([-0.1242])
tensor([0.0555])
tensor([-0.1214])
tensor([0.0564])
tensor([-0.1188])
tensor([0.0570])
tensor([-0.1166])
tensor([0.0572])
tensor([-0.1145])
tensor([0.0571])
tensor([-0.1126])
tensor([0.0569])
tensor([-0.1108])
tensor([0.0566])
tensor([-0.1091])
tensor

tensor([0.0016])
tensor([-0.0030])
tensor([0.0016])
tensor([-0.0030])
tensor([0.0016])
tensor([-0.0029])
tensor([0.0015])
tensor([-0.0029])
tensor([0.0015])
tensor([-0.0029])
tensor([0.0015])
tensor([-0.0028])
tensor([0.0015])
tensor([-0.0028])
tensor([0.0015])
tensor([-0.0027])
tensor([0.0014])
tensor([-0.0027])
tensor([0.0014])
tensor([-0.0027])
tensor([0.0014])
tensor([-0.0026])
tensor([0.0014])
tensor([-0.0026])
tensor([0.0014])
tensor([-0.0026])
tensor([0.0013])
tensor([-0.0025])
tensor([0.0013])
tensor([-0.0025])
tensor([0.0013])
tensor([-0.0025])
tensor([0.0013])
tensor([-0.0024])
tensor([0.0013])
tensor([-0.0024])
tensor([0.0013])
tensor([-0.0024])
tensor([0.0012])
tensor([-0.0023])
tensor([0.0012])
tensor([-0.0023])
tensor([0.0012])
tensor([-0.0023])
tensor([0.0012])
tensor([-0.0022])
tensor([0.0012])
tensor([-0.0022])
tensor([0.0012])
tensor([-0.0022])
tensor([0.0011])
tensor([-0.0022])
tensor([0.0011])
tensor([-0.0021])
tensor([0.0011])
tensor([-0.0021])
tensor([0.0011])
ten

tensor([3.3138e-05])
tensor([-6.2130e-05])
tensor([3.2640e-05])
tensor([-6.1332e-05])
tensor([3.2252e-05])
tensor([-6.0497e-05])
tensor([3.1866e-05])
tensor([-5.9662e-05])
tensor([3.1360e-05])
tensor([-5.8910e-05])
tensor([3.0974e-05])
tensor([-5.8117e-05])
tensor([3.0586e-05])
tensor([-5.7323e-05])
tensor([3.0080e-05])
tensor([-5.6611e-05])
tensor([2.9699e-05])
tensor([-5.5853e-05])
tensor([2.9315e-05])
tensor([-5.5098e-05])
tensor([2.8805e-05])
tensor([-5.4429e-05])
tensor([2.8540e-05])
tensor([-5.3635e-05])
tensor([2.8160e-05])
tensor([-5.2919e-05])
tensor([2.7659e-05])
tensor([-5.2283e-05])
tensor([2.7388e-05])
tensor([-5.1533e-05])
tensor([2.7007e-05])
tensor([-5.0855e-05])
tensor([2.6615e-05])
tensor([-5.0192e-05])
tensor([2.6364e-05])
tensor([-4.9467e-05])
tensor([2.5965e-05])
tensor([-4.8842e-05])
tensor([2.5587e-05])
tensor([-4.8207e-05])
tensor([2.5332e-05])
tensor([-4.7527e-05])
tensor([2.5063e-05])
tensor([-4.6857e-05])
tensor([2.4692e-05])
tensor([-4.6255e-05])
tensor([2.4

tensor([2.0012e-06])
tensor([-4.1453e-06])
tensor([1.8880e-06])
tensor([-4.1410e-06])
tensor([1.7637e-06])
tensor([-4.1426e-06])
tensor([1.8845e-06])
tensor([-4.0218e-06])
tensor([1.7623e-06])
tensor([-4.0253e-06])
tensor([1.8857e-06])
tensor([-3.8974e-06])
tensor([1.7728e-06])
tensor([-3.8927e-06])
tensor([1.8605e-06])
tensor([-3.7935e-06])
tensor([1.7518e-06])
tensor([-3.7873e-06])
tensor([1.8692e-06])
tensor([-3.6686e-06])
tensor([1.7486e-06])
tensor([-3.6677e-06])
tensor([1.8699e-06])
tensor([-3.5448e-06])
tensor([1.7476e-06])
tensor([-3.5469e-06])
tensor([1.8552e-06])
tensor([-3.4350e-06])
tensor([1.7467e-06])
tensor([-3.4251e-06])
tensor([1.8517e-06])
tensor([-3.3185e-06])
tensor([1.7304e-06])
tensor([-3.3183e-06])
tensor([1.8557e-06])
tensor([-3.1897e-06])
tensor([1.7334e-06])
tensor([-3.1913e-06])
tensor([1.8356e-06])
tensor([-3.0813e-06])
tensor([1.7211e-06])
tensor([-3.0795e-06])
tensor([1.8491e-06])
tensor([-2.9535e-06])
tensor([1.6063e-06])
tensor([-3.0332e-06])
tensor([1.7

Look at that !